### ISSUE TITLE
SplitByTopic skill hangs on large text files

### ISSUE THREAD

**Issue by clande** [power-of-language/oneai_sdk_python#4] opened 2023-05-24 19:55 UTC
Hello,

I'm trying to build a knowledge base using the [article](https://www.oneai.com/learn/gpt-assistant?utm_source=newletter&utm_campaign=gpt-assistant&utm_medium=socials) you published on the same topic. The key difference for me is that I don't want to scrape the content from online articles and instead have a text file I want to insert into the collection.

The problem I have is that the text file is too large (4.5MB) or maybe I'm submitting it incorrectly. At any rate it seems that the SplitByTopic skill is just running and running and never returning (I let it run for more than an hour). And also, it seems to block me from being able to submit any other pipelines with that skill.

[Here's](https://github.com/clande/demo/blob/cffba5914fe7ea690cdd5731d73b8a3da9d926ce/oneai_splitbytopic_repro.py) some code that repro's the behavior.

Is there a better way to accomplish this? Some things I've tried are using the other run_* methods in the python SDK and also manually creating a web request and side-stepping the python SDK altogether.

It would be great if there was a way to submit the task and then check back on it periodically. I see that the SDK is doing that for the run_async methods via web requests. It would be really handy if there was an option to break that up into two steps.

Is there a way to cancel a submitted task?

TIA,
Chris

**Comment by michgur** [comment] 2023-05-25 11:37
Hi Chris!
Your code looks fine (though there's no need to use run_batch with a single input),
so it's probably an issue on our backend.

can you send me the file? michael@oneai.com

**Comment by michgur** [comment] 2023-05-25 11:39
other remarks -

- ATM there's no way to "split" the async call in the SDK, may be added in the future
- no way to cancel a task ATM

**Comment by michgur** [comment] 2023-05-25 16:42
closing as the issue is unrelated to the Python SDK

**Closed as completed by michgur** 2023-05-25 16:42 UTC
